---
- name: Update a catalog item in ServiceNow
  hosts: localhost
  gather_facts: no
  
  tasks: 
  
    - name: Retrieve catalog request sysid
      servicenow.itsm.api_info:
        resource: sc_req_item
        sysparm_query: numberSTARTSWITH{{ ticket_number }}
      register: result

    - name: print the result
      ansible.builtin.debug:
        var: result

    - name: Update a catalog work notes and state in ServiceNow
      servicenow.itsm.api:
        action: patch
        resource: sc_req_item
        sys_id: "{{ result.record[0].sys_id }}"
        data:
          request_state: "{{ request_state | default(omit) }}"
          comments: "{{ work_notes }}"
          state: 3