---
- name: Update a catalog item in ServiceNow
  hosts: localhost
  gather_facts: no
  
  tasks: 
  
    - name: Retrieve catalog request sysid
      servicenow.itsm.api_info:
        resource: sc_request
        sysparm_query: numberSTARTSWITH{{ ticket_number }}
      register: requestresult
      when: ticket_number != ''
    
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: requestresult
        verbosity: 2

    #- name: Update a catalog work notes and state in ServiceNow
    #  servicenow.itsm.api:
    #    action: patch
    #    resource: sc_request
    #    sys_id: "{{ requestresult.record[0].sys_id }}"
    #    data:
    #      request_state: "{{ request_state | default(omit) }}"
    #      work_notes: "{{ work_notes }}"
    #  when: ticket_number != '' 